### ISSUE TITLE
zipCode parameter incorrect type

### ISSUE THREAD

**Issue by wmansfield** [westphalen/ng-stripe-checkout#2]
IStripeCheckoutOptions has the zipCode parameter as a string, but stripe expects a boolean.  Notes here: https://stripe.com/docs/checkout#integration-custom.

For Reference: Getting error from stripe:
```
StripeCheckout.open: Type mismatch for option 'zipCode':
Looking for type 'boolean', but instead we found 'string'.
You can learn about the available configuration options in the Checkout docs:
https://stripe.com/docs/checkout
```

**Comment by westphalen** [comment]
Thank you for the opening this bug @wmansfield , do you want to make a pull request to fix this?

**Comment by mfossel** [comment]
I just put in 'true' as a string and it works fine, so not a major problem.

**Comment by westphalen** [comment]
Fixed in https://github.com/westphalen/ng-stripe-checkout/commit/8a5fea52ff18a9eac24c5dbb86a5c07bc6ea171f
