### ISSUE TITLE
Stripe language settings not working properly

### ISSUE THREAD

**Issue by anishcrest** [westphalen/ng-stripe-checkout#5]
Hi there.

Thanks for this wonderful plugin. I have an issue with the locale settings of Stripe checkout. I have used it in my ionic 3 project. I have set the locale to "es" and it works fine for the textbox placeholders like below:
![image](https://user-images.githubusercontent.com/37139762/39755618-2c599046-52e4-11e8-9942-f3c1ead8106f.png)

But it shows the errors for cards in English irrespective of the locale set. It looks like below:
![image](https://user-images.githubusercontent.com/37139762/39755678-6a63a142-52e4-11e8-8e56-5b5106691b13.png)

I have the same stripe checkout popup in my website and it works fine.

Below is a snippet to my configuration code:
![image](https://user-images.githubusercontent.com/37139762/39755718-8bf6a034-52e4-11e8-8df8-39fe3fe96b6d.png)

Please help me with this

**Comment by westphalen** [comment]
Perhaps Stripe is picking up the browser locale for some of its content.

Did you already reach out to Stripe about this?

**Comment by anishcrest** [comment]
Thanks, Have sent an email to Stripe support. Will let you know what they have for the issue.
Thanks again.

**Comment by anishcrest** [comment]
Hi. Sorry for the late reply.
I have been informed from Stripe that its an issue from their side.

Thanks..
